language: java
sudo: true
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD_NEW" | docker login -u "$DOCKER_USERNAME_NEW" --password-stdin
  - docker pull postgres:9.6.12
  -
jobs:
  include:
    - stage: build with maven & generate reports
      script:
        - mvn clean verify jacoco:report coveralls:report
    - stage: build docker images for server and agent
      if: NOT branch = master OR type IN (pull_request)
      script:
        - mvn validate docker:build@build-docker -P docker-app -f ./judge-d-server/pom.xml
        - mvn validate docker:build@build-docker -P docker-app -f ./judge-d-agent/pom.xml
    - stage: build & publish docker image for server
      if: branch = master AND NOT type IN (pull_request)
      script:
        - mvn validate docker:build@build-docker -P docker-app -f ./judge-d-server/pom.xml
        - echo "Pushing to docker registry"
        - echo "$DOCKER_PASSWORD_NEW" | docker login -u "$DOCKER_USERNAME_NEW" --password-stdin
        - docker push hltech/judge-d
        - echo "Pushing to heroku registry"
        - docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
        - docker tag hltech/judge-d registry.heroku.com/judge-d/web
        - docker push registry.heroku.com/judge-d/web
    - stage: release app in heroku
      if: branch = master AND NOT type IN (pull_request)
      script:
        - heroku container:release web -a judge-d
    - stage: build & publish docker image for agent
      if: branch = master AND NOT type IN (pull_request)
      script:
        - mvn validate docker:build@build-docker -P docker-app -f ./judge-d-agent/pom.xml
        - echo "$DOCKER_PASSWORD_NEW" | docker login -u "$DOCKER_USERNAME_NEW" --password-stdin
        - docker push hltech/judge-d-agent
